---
- name: To set up the .ssh dir and paste the id_rsa.pub from master to local.
  host: app_server
  become:
  task:
  - name: Ensure .ssh directory exists
    ansible.builtin.file:
      path: /home/ec2-user/.ssh
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: "0700"

  - name: Add authorized_keys file
    ansible.builtin.file:
      path: /home/ec2-user/.ssh/authorized_keys
      state: touch
      owner: ec2-user
      group: ec2-user
      mode: "0600"

  - name: Copy id_rsa.pub from master to worker nodes
    ansible.builtin.authorized_key:
      user: <username>  # Specify the username of the user on the worker nodes
      key: "{{ lookup('file', '/path/to/id_rsa.pub') }}"  # Path to the id_rsa.pub file on the master node
    delegate_to: localhost  # Run the task on the Ansible control node (master node)



